### ISSUE TITLE
Collector crashes after timeouts?

### ISSUE THREAD

**Issue by alexkazeko** [percona/mongodb_exporter#39] opened 2017-01-23 15:18 UTC
Hello, 

I've got PMM agent monitoring linux:metrics and mongodb:metrics. From time to time mongodb exporter crashes. Here is what I see in logs:

```
### Warning: the exporter is in beta/experimental state and field names are very
### likely to change in the future and features may change or get removed!
### See: https://github.com/Percona-Lab/prometheus_mongodb_exporter for updates
mongodb_exporter version: 1.0.5, git commit hash: 4651d4d535ed6c807606daf6a864338c90e06e35
Listening on 10.81.120.79:42003
E0123 07:18:08.927387    2341 connection.go:27] Cannot connect to server using url mongodb://xxx$@localhost:27017: read tcp 127.0.0.1:34918->127.0.0.1:27017: i/o timeout
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5f0b9e]

goroutine 41467 [running]:
panic(0x74e180, 0xc420012050)
	/usr/local/go1.7.1/src/runtime/panic.go:500 +0x1a1
gopkg.in/mgo%2ev2.(*Session).Close(0x0)
	/mnt/workspace/pmm-client-tarball/pmm-client-1.0.5/src/gopkg.in/mgo.v2/session.go:1612 +0x2e
github.com/Percona-Lab/prometheus_mongodb_exporter/collector.(*MongodbCollector).Collect(0xc42015fea0, 0xc420750180)
	/mnt/workspace/pmm-client-tarball/pmm-client-1.0.5/src/github.com/Percona-Lab/prometheus_mongodb_exporter/collector/mongodb_collector.go:76 +0xa1
github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func2(0xc420344100, 0xc420750180, 0x93db20, 0xc42015fea0)
	/mnt/workspace/pmm-client-tarball/pmm-client-1.0.5/src/github.com/prometheus/client_golang/prometheus/registry.go:433 +0x63
created by github.com/prometheus/client_golang/prometheus.(*Registry).Gather
	/mnt/workspace/pmm-client-tarball/pmm-client-1.0.5/src/github.com/prometheus/client_golang/prometheus/registry.go:434 +0x326
```

MongoDB version : "3.2.9-2.1". This node is a master of a 3-node replica set, but I've seen same logs on other nodes - crash after the timeout.

Alex

**Comment by timvaillancourt** [comment] 2017-02-22 14:22
Hello @alexkazeko, thanks for reporting this. I've been meaning to fix this and currently this is known behaviour. 'pmm-admin restart --all' will restart the exporter as a workaround.

I plan to rework the connection code to retry on failure, just out of cycles at the moment. Any code changes are appreciated in the meantime!

**Comment by timvaillancourt** [comment] 2017-03-09 01:00
Closing as duplicate of #50.

PR #55 fixes this issue, stay tuned.

**Closed by timvaillancourt** 2017-03-09 01:00 UTC
