### ISSUE TITLE
$collstats not working with mongodb 5.0

### ISSUE THREAD

**Issue by hustxx** [percona/mongodb_exporter#381] opened 2021-11-14 00:04 UTC
Tried this with my mongodb 5.0 setup, keep getting the following failure, any suggestions?

/usr/local/bin/mongodb_exporter --mongodb.uri=mongodb://mongodb_exporter:password@localhost:27017/admin --mongodb.collstats-colls=db.col1

ERRO[0002] cannot get $collstats cursor for collection db.col1: (Location40415) BSON field '$collStats.latencyStats.key' is an unknown field. 
ERRO[0007] cannot get $collstats cursor for collection db.col1: (Location40415) BSON field '$collStats.latencyStats.key' is an unknown field.

**Comment by zekena2** [comment] 2022-05-26 10:12
Same for me in mongodb v4.2 with flags `--compatible-mode --discovering-mode --collect-all`
But I get all sorts of errors like

Failed to get $dbstats for database test 
Failed to get $dbstats for database local 
Failed to get $dbstats for database config

cannot get $collstats cursor for collection 
cannot get $indexStats cursor for collection ....  timed out while checking out a connec tion from connection pool: context canceled; maxPoolSize: 100, connections in use by cursors: 0, connections in use by transactions: 0, connections in use by other ope rations: 0
these two errors happen with almost all collections.

**Comment by denisok** [comment] 2022-06-09 10:50
@zekena2 what mongodb_exporter version do you use?

**Comment by percona-csalguero** [comment] 2022-06-17 21:05
I cannot reproduce the issue.

Using MongoDB 5.0
```
rs1:PRIMARY> db.version()
5.0.9
```
Running the exporter against the primary:
```bash
./mongodb_exporter --mongodb.uri=mongodb://127.0.0.1:17001/admin --collect-all --discovering-mode --compatible-mode
```
There is a database `test` I've created and the collection `col1` having at least 1 document.
A curl gets this output:
```bash
curl --silent http://localhost:9216/metrics | grep mongodb_collstats | head -n 3
```
```
# HELP mongodb_collstats_latencyStats_commands_latency collstats.latencyStats.commands.
# TYPE mongodb_collstats_latencyStats_commands_latency untyped
mongodb_collstats_latencyStats_commands_latency{cl_id="62ace9611bb9c99d87bc2418",cl_role="shardsvr",collection="col1",database="test",rs_nm="rs1",rs_state="1"} 0
```

**Comment by zekena2** [comment] 2022-06-17 23:54
I tried on a lighter database in terms of data and connections and it didn't give these errors. so it might be hitting some timout when the database is busy?

**Comment by percona-csalguero** [comment] 2022-06-20 11:22
Yes, I am pretty confident that's the real problem.
It might even be the number of databases. If the number of databases/collections is high, calling `list Databases` or `list Collections` in discovering mode could be taking too much time.

**Comment by percona-csalguero** [comment] 2022-06-20 11:34
Hi @zekena2 , I am going to close this ticket.
Please if you can tell us how to reproduce the issue, open a new issue here with the step by step instructions.
If you can include environmental information that would be great help.

Regards

**Closed by percona-csalguero** 2022-06-20 11:34 UTC
Labels: bug, community, triage, cannot reproduce
